web:
    build: .
    ports:
    - "8080:8080"
    links:
    - postgres
    container_name: b2cweb
postgres:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_DB: b2c_database
      POSTGRES_USER: b2cuser
      POSTGRES_PASSWORD: post1234
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/scripts/schema.sql:/docker-entrypoint-initdb.d/createschema.sql
        - ./postgres/scripts/metadata.sql:/docker-entrypoint-initdb.d/metadata.sql
        - ./postgres/scripts/testdata.sql:/docker-entrypoint-initdb.d/testdata.sql
